### ISSUE TITLE
Installation won't work with new sqlalchemy==1.4.0

### ISSUE THREAD

**Issue by myOmikron** [tulir/mautrix-telegram#597]
I've tried to install mautrix-telegram, but was only successful after downgrading sqlalchemy from 1.4.0 to 1.3.23.
```
(venv) [mautrix-telegram@matrix venv]$ python -m mautrix_telegram -g
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/mautrix-telegram/venv/lib/python3.9/site-packages/mautrix_telegram/__main__.py", line 22, in <module>
    from mautrix.util.db import Base
  File "/opt/mautrix-telegram/venv/lib/python3.9/site-packages/mautrix/util/db/__init__.py", line 1, in <module>
    from .base import Base, BaseClass
  File "/opt/mautrix-telegram/venv/lib/python3.9/site-packages/mautrix/util/db/base.py", line 11, in <module>
    from sqlalchemy.engine.result import RowProxy, ResultProxy
ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine.result' (/opt/mautrix-telegram/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py)
```

**Comment by tulir** [comment]
Duplicate of #595

**Comment by benneti** [comment]
would you consider to tag a new (point-)release to fix the installation process?
